#!/bin/sh

wan_detect_mode="$(uci get wanDetect.settings.mode)"
if [ "$wan_detect_mode" = "test1" ]; then
	if [ "$ACTION" = "released" -a -f "/tmp/reset_pressed" ]; then
		echo 1 > /tmp/button_reset_check
	elif [ "$ACTION" = "pressed" ]; then
		touch /tmp/reset_pressed
	fi

	[ -f "/tmp/g_wifi_not_cal" ] && exit 0
fi

[ -e /tmp/done_boot ] || exit 0

if [ "$ACTION" = "pressed" ]; then
	#[X80_5G]reset button didnot work
	local isMobile=$(isMobile 2>/dev/null)
	if [ "$isMobile" = "yes" -a "$wan_detect_mode" = "test1" ]; then
		exit 0
	fi
    ubus call leds device '{"state":"resetting"}'
    lua -l luci.model.app_cloudfirm -e 'luci.model.app_cloudfirm.config_factory()'
fi
