#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1
PROG_ARPING=/usr/bin/client_mgmt_arping
PROG=/usr/bin/client_mgmt
PROG_UPLOAD=/usr/bin/client_upload
local TM_CLIENT_MGMT_PATH=/tmp/client_mgmt

start_service()
{
    local factory_mode=0
	config_load wifi
	config_get factory_mode ap factorymode '0'

	if [ "1" = "$factory_mode" ];then
		return 0
	fi

	if [ ! -d $TM_CLIENT_MGMT_PATH ]; then
		mkdir $TM_CLIENT_MGMT_PATH
	fi

    if [ -f /tmp/g_factorymode ]; then
        return 0
    fi

    sysmode=$(uci get sysmode.sysmode.mode)
    if [ "$sysmode" == "Router" ]; then
        procd_open_instance
        procd_set_param command "$PROG_ARPING" -t 10 -o 180 -p 30 -a
        procd_set_param respawn
        procd_close_instance
    fi
    procd_open_instance
    procd_set_param command "$PROG"
    procd_set_param respawn
    procd_close_instance

    procd_open_instance
    procd_set_param command "$PROG_UPLOAD"
    procd_set_param respawn
    procd_close_instance

    open_client_triggers &

    /usr/sbin/manager_role_set
}
