#!/bin/sh /etc/rc.common

START=98
USE_PROCD=1

start_service() 
{	
	procd_open_instance    	
	procd_set_param command /usr/bin/cloud-brd -c /etc/cloud_config.cfg    	
	procd_set_param respawn    	
	procd_close_instance
}

restart()
{
    rm /tmp/cloud/cloud_status_check_done
    stop
    start
    /etc/init.d/cloud_client restart
}
