#!/bin/sh /etc/rc.common

START=99
SERVICE_DAEMONIZE=1

start()
{
    /usr/sbin/cloud_account_modify
	service_start /usr/bin/cloud-client
}

stop()
{
	service_stop /usr/bin/cloud-client
}

restart()
{
	stop
	start
}
