#!/bin/sh /etc/rc.common
# Copyright (c) 2020 Shenzhen TP-LINK Technologies Co.Ltd.
# Author		Song Tianhao<songtianhao@tp-link.com.cn>


START=99
STOP=99

USE_PROCD=1

reload_service() {
	local ddns_provider
    
    ddns_provider=$(uci get ddns.provider.provider)

    if [ "$ddns_provider" == "noip" ]; then
        local noip_is_on
        noip_is_on=$(uci get ddns.noip.enabled)
        if [ "$noip_is_on" == "on" ]; then
            /usr/sbin/ddns start noip
        fi
    elif [ "$ddns_provider" == "dyndns" ]; then
        local dyn_is_on
        dyn_is_on=$(uci get ddns.dyndns.enabled)
        if [ "$dyn_is_on" == "on" ]; then
            /usr/sbin/ddns start dyndns
        fi
    fi
}


service_triggers() {
	procd_add_reload_trigger "ddns"
}
