#!/bin/sh /etc/rc.common

START=99
STOP=99

USE_PROCD=1
. /lib/functions.sh

local is_tm_shn_support
local UCI_CONFIG_DIR="/etc/profile.d"
config_load profile
unset UCI_CONFIG_DIR
config_get is_tm_shn_support "tm_shn" "support" "yes"
config_clear

start_service() {
    local sysmode=$(cat /tmp/sys_mode)
    local device_type
    device_id=$(getfirm DEV_ID)
    config_load bind_device_list
    config_get device_type $device_id role "UNBIND"

    if [ "$sysmode" == "Router" ] && [ "$device_type" == "AP" ]; then
        local guest_enable
        local bw_limit_enable
        local bw_limit_down
        local bw_limit_up

        config_load wifi
        config_get guest_enable "guest" "enable" "0"
        config_get bw_limit_enable "guest" "bw_limit_enable" "0"
        config_get bw_limit_down "guest" "bw_limit_down" "1024000"
        config_get bw_limit_up "guest" "bw_limit_up" "1024000"

        local bps_rx=$((bw_limit_down * 1024))
        local bps_tx=$((bw_limit_up * 1024))
        if [ $guest_enable = "1" ] && [ $bw_limit_enable = "1" ]; then
            bw_limit_enable="1"
        else
            bw_limit_enable="0"
        fi

        modprobe traffic_control
        echo "bps_rx $bps_rx" > /proc/traffic_control/guest
        echo "bps_tx $bps_tx" > /proc/traffic_control/guest
        echo "enable $bw_limit_enable" > /proc/traffic_control/guest
    fi
}

stop_service() {
    echo "enable 0" > /proc/traffic_control/guest
}

service_triggers() {
    procd_add_reload_trigger "wifi"
}
