#!/bin/sh /etc/rc.common

START=99
STOP=99

USE_PROCD=1
PROG=/usr/sbin/guest-schedule

. /lib/functions.sh

start_service() {
    local sysmode=$(cat /tmp/sys_mode)
    local device_type
    device_id=$(getfirm DEV_ID)
    config_load bind_device_list
    config_get device_type $device_id role "UNBIND"

    if [ "$sysmode" == "Router" ] && [ "$device_type" == "AP" ]; then
        procd_open_instance
        procd_set_param command "$PROG"
        procd_close_instance
    fi
}

service_triggers() {
    procd_add_reload_trigger "wifi"
}

reload_service() {
    ubus call guest-schedule reload &
    start
}
