#!/bin/sh /etc/rc.common
# Copyright (c) 2016 Shenzhen TP-LINK Technologies Co.Ltd.
# Author		Wang Hao<wanghao@tp-link.com.cn>

SERVICE_DAEMONIZE=1

START=99
STOP=99

local HAND_RADAR_CONFIG_FILE=/tmp/handheld_radar.conf

add() {
    local value=$1
    echo "$value" >> $HAND_RADAR_CONFIG_FILE
}

_get_ifname() {
    local config="$1"
    local vapname net_type device

    config_get vapname "$config" vapname
    config_get net_type "$config" type
    config_get device "$config" device

    if [ -n "$vapname" ] && [ "$device" = "wifi0" ] && [ "$net_type" = "default" ]; then
        # 24G
        default_2g="$vapname"
    elif [ -n "$vapname" ] && [ "$device" = "wifi1" ] && [ "$net_type" = "default" ]; then
        # 5G1
        default_5g="$vapname"
    elif [ -n "$vapname" ] && [ "$device" = "wifi2" ] && [ "$net_type" = "default" ]; then
        # 5G2
        default_5g2="$vapname"
    fi
}


generate_wifi_ifnames() {
    local default_ifnames

    default_2g=
    default_5g=
    default_5g2=

    echo -n "" > $HAND_RADAR_CONFIG_FILE

    config_load wireless
    config_foreach _get_ifname wifi-iface

    # if no 5G2 default ath25
    if [ -n "$default_5g2" ]; then
        default_ifnames="$default_2g,$default_5g,${default_5g2}"
    else
        default_ifnames="$default_2g,$default_5g,ath25"
    fi

    add "default_ifnames=$default_ifnames"

    config_clear
}

start() {

	generate_wifi_ifnames

    if [[ "$(uci get bluetooth.settings.mode)" == "normal" ]]; then
        /usr/sbin/handheld_radar -s
    fi
	return 0
}
