#!/bin/sh /etc/rc.common

START=21
STOP=21

USE_PROCD=1

__init_dev() {
    local gpio_dev="/dev/gpio"
    [[ -c ${gpio_dev} ]] || {
        local name=$(cat /proc/devices | grep gpio | sed  -r -n "s/[0-9]+ //p")
        [[ -z ${name} ]] && return 1

        local num=$(cat /proc/devices | grep gpio | sed  -r -n "s/ [a-z0-9]*//p")
        [[ -z ${num} ]] && return 1

        mknod ${gpio_dev} c ${num} 0
    }
    return 0
}

start_service() {
    __init_dev

    procd_open_instance
    procd_set_param command /usr/bin/leds -l i
    procd_set_param respawn 3600 5 5

    procd_close_instance

    return 0
}

stop_service() {
    return 0
}

reload_service() {
    stop
    start
}