#!/bin/sh /etc/rc.common
# Copyright (c) 2016 Shenzhen TP-LINK Technologies Co.Ltd.
# Author		Wang Hao<wanghao@tp-link.com.cn>

START=75
STOP=75

USE_PROCD=1

start_service() {
    local enable
    local led_status
    local time_begin 
    local time_end
	enable=$(uci get leds.night_mode.enable)
	led_status=$(uci get leds.settings.enable)
	time_begin=$(uci get leds.night_mode.time_begin)
	time_end=$(uci get leds.night_mode.time_end)
	killall leds_set_nightmode

    if [[ "$led_status" = "off" ]]; then
        /etc/tsched.d/leds_schedule TURN_OFF
        return 0
    elif [[ "$enable" = "off" ]]; then
        /etc/tsched.d/leds_schedule TURN_ON
        return 0
    fi

	leds_set_nightmode "$enable" "$time_begin" "$time_end" > /dev/null 2>&1 &	

	return 0
}

stop_service() {
	tsched_conf -D leds_schedule
	tsched_conf -u leds_schedule
	
	return 0
}

reload_service() {
	#stop
	start
}

service_triggers() {
    procd_add_reload_trigger "leds"
}
