#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1
PROG=/usr/bin/msgcenterd

local TEMP_UCI_PATH=/tmp/tmp-device-config
local MSG_UCI_FILE=/tmp/tmp-device-config/message_center

start_service()
{
	if [ ! -f $MSG_UCI_FILE ]; then
		if [ ! -d $TEMP_UCI_PATH ]; then
			mkdir $TEMP_UCI_PATH
		fi
		cp /etc/config/message_center $TEMP_UCI_PATH
	fi
	
    procd_open_instance
    procd_set_param command "$PROG"
    procd_set_param respawn
    procd_close_instance
}
