#!/bin/sh /etc/rc.common
# Copyright (c) 2016 Shenzhen TP-LINK Technologies Co.Ltd.
# Author		Wang Hao<wanghao@tp-link.com.cn>

START=87

# script defined in product_configs folder
[ -f "/lib/switch/core.sh" ] && . /lib/switch/core.sh

WAIT_FOR_WIFI_DONE=0
WIFI_CALED_FILE="/tmp/wifi_is_cal"
WIFI_SET_DONE_FILE="/tmp/wifi_set_done"

start() {

	if [ "$WAIT_FOR_WIFI_DONE" = "1" ];then

		config_load wifi
		config_get factorymode ap factorymode '0'
		config_clear
		# up eth0 after wifi set done
		if [ "$factorymode" = 1 -a -f $WIFI_CALED_FILE ]; then
			for i in `seq 10`
			do
				if [ -f $WIFI_SET_DONE_FILE ]; then
					#echo "wifi set up OOOOKKKKKKK" > /dev/console
					break
				else
					#echo "wifi is setting" > /dev/console
					sleep 1
				fi
			done
	    fi
	fi

	echo "=====ifconfig eth0 up ======" > /dev/console
	ifconfig eth0 up
	touch /tmp/eth_up

	# turn on phy link
	setup_ports
    touch /tmp/phyup_file

	return 0
}

stop() {
	
	return 0
}
