#!/bin/sh /etc/rc.common
# Copyright (c) 2016 Shenzhen TP-LINK Technologies Co.Ltd.
# Author		Wang Hao<wanghao@tp-link.com.cn>

START=42

start() {

    config_load wifi
    config_get factorymode ap factorymode '0'
    config_clear

    if [[ "$factorymode" = 1 ]] && [[ -f /tmp/wifi_is_cal ]]; then
		ifconfig eth0 down
		echo "=====ifconfig eth0 down = 42 ===" > /dev/console
    fi

	return 0
}

stop() {

	return 0
}
