#!/bin/sh /etc/rc.common

START=99
STOP=99

USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/rsched
    # procd_set_param respawn 3600 10 1

    procd_close_instance

    return 0
}

stop_service() {
    tsched_conf -D  reboot_schedule
    tsched_conf -u  reboot_schedule

    return 0
}

reload_service() {
    #echo device_schedule init reload > /dev/console
    stop
    start
}

service_triggers() {
    procd_add_reload_trigger "reboot_schedule"
}
