#!/bin/sh /etc/rc.common
# Copyright (C) 2017 Tp-link.com
# Author: Xu Shengfu <xushengfu@tp-link.com.cn>
# Date: 27Nov17

START=86
# stop before leds
STOP=10

USE_PROCD=1
PROG=/usr/sbin/server-probe

. /lib/functions.sh

start_service() {
    config_load server_probe
    config_get_bool enabled server_probe 'enabled' '0'
    [ "$enabled" -gt 0 ] || {
        return 1
    }
    config_clear

    procd_open_instance
    procd_set_param command "$PROG" -l n
    procd_set_param respawn
    procd_close_instance
}
