#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=30

boot() {
#	/etc/init.d/deviceInfo load_runtime_info
#	/usr/bin/logd > /dev/null 2>&1 &
	#/etc/init.d/wifi setup
#	dhcp_hook_d > /dev/null 2>&1 &
#	/etc/init.d/monitor start
#	/etc/init.d/smartip start
#	gpiod > /dev/null 2>&1 &
#	/etc/init.d/ledCtrl startup
#   /etc/init.d/powerCtrl startup
#   /etc/init.d/timerjob startup
#	/etc/init.d/timedst startup
	if [ ! -s /etc/config/bind_device_list ]; then
		tddp > /dev/null 2>&1 &
	fi
#	tmpServer > /dev/null 2>&1 &
}
