#!/bin/sh /etc/rc.common
# Copyright(c) 2008-2014 Shenzhen TP-LINK Technologies Co.Ltd.
#
# Details : The init script for tsched.
# Author  : Ye Qianchuan <yeqianchuan@tp-link.net>
# Version : 1.0
# Date    : 27 Mar, 2014

START=50

USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/sbin/tsched
    procd_set_param respawn
    procd_close_instance
    return 0
}

stop_service() {
    echo "WARNING: It is possible to cause troubles if you stop it." 1>&2
    return 0
}
