#!/bin/sh /etc/rc.common
# Copyright (C) 2010 Jo-Philipp Wich

START=50

USE_PROCD=1

UHTTPD_BIN="/usr/sbin/uhttpd"
PX5G_BIN="/usr/sbin/px5g"
OPENSSL_BIN="/usr/bin/openssl"

append_arg() {
	local cfg="$1"
	local var="$2"
	local opt="$3"
	local def="$4"
	local val

	config_get val "$cfg" "$var"
	[ -n "$val" -o -n "$def" ] && procd_append_param command "$opt" "${val:-$def}"
}

append_bool() {
	local cfg="$1"
	local var="$2"
	local opt="$3"
	local def="$4"
	local val

	config_get_bool val "$cfg" "$var" "$def"
	[ "$val" = 1 ] && procd_append_param command "$opt"
}

generate_keys() {
	local cfg="$1"
	local key="$2"
	local crt="$3"
	local days bits country state location commonname

	config_get days       "$cfg" days
	config_get bits       "$cfg" bits		'2048'
	config_get country    "$cfg" country	'CN'
	config_get state      "$cfg" state
	config_get location   "$cfg" location
	config_get commonname "$cfg" commonname

	bits=2048
	commonname="tplinkdeco.net"

	if [ -x "$OPENSSL_BIN" ]; then
	{
		# preparation according to /etc/ssl/openssl.cnf
		CA_PATH=/etc/ssl/demoCA
		mkdir -p $CA_PATH/private
		mkdir -p $CA_PATH/newcerts
		touch $CA_PATH/index.txt
		
		# this dates are set specifically to fix issues on Chrome for MacOS
		startdate='100101000000Z'
		enddate='301231000000Z'

		# generate key and cert for CA
		$OPENSSL_BIN req -x509 -newkey rsa:$bits -nodes -keyout "$CA_PATH/private/cakey.pem" -out "$CA_PATH/cacert.pem" \
			-subj "/C=$country/CN=$commonname" -batch
		# generate key and signing request for uhttpd host
		$OPENSSL_BIN req -newkey rsa:$bits -nodes -keyout $UHTTPD_KEY -out $UHTTPD_CERT.csr \
			-subj "/C=$country/CN=$commonname" -batch
		# sign the signing request with CA
		$OPENSSL_BIN ca -in $UHTTPD_CERT.csr -out $UHTTPD_CERT -create_serial -policy policy_anything -startdate $startdate -enddate $enddate -batch

		rm -rf $CA_PATH
		rm -f $UHTTPD_CERT.csr
	}
	else
	[ -x "$PX5G_BIN" ] && {
		$PX5G_BIN selfsigned -der \
			-days ${days:-730} -newkey rsa:${bits:-1024} -keyout "${UHTTPD_KEY}.new" -out "${UHTTPD_CERT}.new" \
			-subj /C="${country:-DE}"/ST="${state:-Saxony}"/L="${location:-Leipzig}"/CN="${commonname:-OpenWrt}"
		sync
		mv "${UHTTPD_KEY}.new" "${UHTTPD_KEY}"
		mv "${UHTTPD_CERT}.new" "${UHTTPD_CERT}"
	}
    fi
}

start_instance()
{
	UHTTPD_CERT=""
	UHTTPD_KEY=""

	local cfg="$1"
	local realm="$(getfirm MODEL)"
	local https_support="$(uci -c /etc/profile.d get profile.@https_mgnt[0].https_support)"
	local redirect_to_https="$(uci -c /etc/profile.d get profile.@webui_mgnt[0].redirect_https)"
	local system_mode="$(uci get sysmode.sysmode.mode)"
	local webui_support=""
	local listen http https interpreter indexes path handler

	if [ "$system_mode" == "Router" ]; then
		webui_support="$(uci -c /etc/profile.d get profile.@webui_mgnt[0].routermode_support)"
	elif [ "$system_mode" == "AP" ]; then
		webui_support="$(uci -c /etc/profile.d get profile.@webui_mgnt[0].apmode_support)"
	fi

	procd_open_instance
	procd_set_param respawn
	procd_set_param stderr 1
	procd_set_param command "$UHTTPD_BIN" -f

	append_arg "$cfg" home "-h"
	append_arg "$cfg" realm "-r" "${realm:-OpenWrt}"
	append_arg "$cfg" config "-c"
	append_arg "$cfg" cgi_prefix "-x"
	[ -f /usr/lib/uhttpd_lua.so ] && {
		config_get handler "$cfg" lua_handler
		[ -f "$handler" ] && append_arg "$cfg" lua_prefix "-l" && {
			procd_append_param command "-L" "$handler"
		}
	}
	[ -f /usr/lib/uhttpd_ubus.so ] && {
		append_arg "$cfg" ubus_prefix "-u"
		append_arg "$cfg" ubus_socket "-U"
		append_bool "$cfg" ubus_cors "-X" 0
	}
	local oversized_script_timeout=""
	oversized_script_timeout="$(uci -c /etc/profile.d get profile.oversized_firmware.script_timeout)"
	if [ "$oversized_script_timeout" == "" ]; then
		append_arg "$cfg" script_timeout "-t"
	else
		procd_append_param command "-t" "$oversized_script_timeout"
	fi
	local oversized_network_timeout=""
	oversized_network_timeout="$(uci -c /etc/profile.d get profile.oversized_firmware.network_timeout)"
	if [ "$oversized_network_timeout" == "" ]; then
		append_arg "$cfg" network_timeout "-T"
	else
		procd_append_param command "-T" "$oversized_network_timeout"
	fi
	append_arg "$cfg" http_keepalive "-k"
	append_arg "$cfg" tcp_keepalive "-A"
	append_arg "$cfg" error_page "-E"
	append_arg "$cfg" max_requests "-n" 3
	append_arg "$cfg" max_connections "-N"

	append_bool "$cfg" no_ubusauth "-a" 0
	append_bool "$cfg" no_symlinks "-S" 0
	append_bool "$cfg" no_dirlists "-D" 0
	append_bool "$cfg" rfc1918_filter "-R" 0

	config_get alias_list "$cfg" alias
	for alias in $alias_list; do
		procd_append_param command -y "$alias"
	done

	config_get http "$cfg" listen_http
	for listen in $http; do
		if [ "${listen#*:}" != "80" ] || [ "$webui_support" == "yes" ]; then
			if [ "${listen#*:}" != "30000" ]; then
		 		procd_append_param command -p "$listen"
			fi
		fi
	done

	config_get interpreter "$cfg" interpreter
	for path in $interpreter; do
		procd_append_param command -i "$path"
	done

	config_get indexes "$cfg" index_page
	for path in $indexes; do
		procd_append_param command -I "$path"
	done

	config_get https "$cfg" listen_https
	config_get UHTTPD_KEY  "$cfg" key  /etc/uhttpd.key
	config_get UHTTPD_CERT "$cfg" cert /etc/uhttpd.crt

	[ -f /lib/libustream-ssl.so ] && [ -n "$https" ] && [ "$https_support" == "yes" ] && [ "$webui_support" == "yes" ] &&  {
		[ -s "$UHTTPD_CERT" -a -s "$UHTTPD_KEY" ] || {
			config_foreach generate_keys cert
		}

		[ -f "$UHTTPD_CERT" -a -f "$UHTTPD_KEY" ] && {
			append_arg "$cfg" cert "-C"
			append_arg "$cfg" key  "-K"

			for listen in $https; do
				procd_append_param command -s "$listen"
			done
		}

		if [ -n "$redirect_to_https" ]; then
			[ "$redirect_to_https" = 1 ] && {
			procd_append_param command "-q"
			}
		else
			append_bool "$cfg" redirect_https "-q" 0
		fi
	}

	for file in /etc/uhttpd/*.json; do
		[ -s "$file" ] && procd_append_param command -H "$file"
	done

	procd_close_instance
}

service_triggers()
{
	procd_add_reload_trigger "uhttpd"
}

start_service() {
	config_load uhttpd
	config_foreach start_instance uhttpd
}

__rc_procd() {
	procd_open_service "uhttpd" "/etc/init.d/uhttpd"
	start_service
	procd_close_service
	}

__boot() {
	__rc_procd
	if eval "type service_started" 2>/dev/null >/dev/null; then
			service_started
	fi
}

boot() {
	# boot in the background.
	__boot &
}

