#!/bin/sh /etc/rc.common
# Copyright (c) 2016 Shenzhen TP-LINK Technologies Co.Ltd.
# Author		Wang Hao<wanghao@tp-link.com.cn>

SERVICE_DAEMONIZE=1

START=84
STOP=84

BR_NAME=br-wan

start() {
	brctl setfd ${BR_NAME} 0
	brctl stp ${BR_NAME} off
	echo 0 > /sys/devices/virtual/net/${BR_NAME}/bridge/multicast_snooping
	#brctl addif br-lan eth0
	#ifconfig eth0 up
	#ifconfig eth1 up
	
	service_start /usr/bin/wanDetection
	
	return 0
}

stop() {
	service_stop /usr/bin/wanDetection
	
	return 0
}
