#!/bin/sh /etc/rc.common
# Copyright (C) 2018 Tp-link.com
# Author: xsfour <xushengfu@tp-link.com.cn>
# Date: 17Mar18

# boot after repacd
START=87
# stop before leds
STOP=20

. /lib/functions.sh

USE_PROCD=1
PROG=/usr/sbin/wpsd

DEBUG_OUTOUT=1
LEVEL=6

conf_path="/etc/wpsd.conf"
tmp_conf_path="/tmp/wpsd_tmp.conf"

wpsd_echo() {
    if [ "$DEBUG_OUTOUT" -gt 0 ]; then
        logger -p $LEVEL "wps: $1"
        echo "wps: $1" >> /dev/console
    fi
}

__write_conf() {
    local ifname=$1
    local conf_path=$2

    [ -n "$ifname" ] || {
        return 1
    }

    local enable=$(uci get wifi.ap.enable 2>/dev/null)
    local enable_2g=$(uci get wifi.ap.enable_2g 2>/dev/null)
    local enable_5g=$(uci get wifi.ap.enable_5g 2>/dev/null)

    if [ -z "${enable}" ]; then
        wpsd_echo "${ifname} disabled"
    elif [ ${enable} = "1" ]; then
        if [ "${ifname}" = "ra2" ]; then
            if [ -z "${enable_2g}" ]; then
                wpsd_echo "${ifname} enabled"
                echo ${ifname} >> ${conf_path}
            elif [ "${enable_2g}" = "1" ]; then
                wpsd_echo "${ifname} enabled"
                echo ${ifname} >> ${conf_path}
            else
                wpsd_echo "${ifname} disabled"
            fi
        elif [ "${ifname}" = "rai2" ] || [ "${ifname}" = "rax2" ]; then
            if [ -z "${enable_5g}" ]; then
                wpsd_echo "${ifname} enabled"
                echo ${ifname} >> ${conf_path}
            elif [ "${enable_5g}" = "1" ]; then
                wpsd_echo "${ifname} enabled"
                echo ${ifname} >> ${conf_path}
            else
                wpsd_echo "${ifname} disabled"
            fi
        else
            wpsd_echo "${ifname} unknown"
        fi
    else
        wpsd_echo "${ifname} disabled"
    fi
}

start_service() {
    wpsd_echo "wpsd start"
    config_load wps
    config_get enabled wpsd enabled 1
    [ "$enabled" -gt 0 ] || {
        config_clear
        return 1
    }

    > ${conf_path}
    config_foreach __write_conf wifi-iface ${conf_path}
    config_clear

    procd_open_instance
    procd_set_param command "$PROG" -c ${conf_path} -l i
    procd_set_param respawn
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger "wifi"
}

stop_service() {
    wpsd_echo "stopping"
    service_stop ${PROG}
    wpsd_echo "stopped"
}

reload_service() {
    wpsd_echo "wpsd reload"
    
    local old_md5_sum="0"
    local new_md5_sum="1"

    [ -f "$conf_path" ] && {
        old_md5_sum=$(md5sum $conf_path| cut -d ' ' -f1)
    }

    config_load wps
    > ${tmp_conf_path}
    config_foreach __write_conf wifi-iface ${tmp_conf_path}
    config_clear

    new_md5_sum=$(md5sum $tmp_conf_path| cut -d ' ' -f1)

    [ "${new_md5_sum}" = "${old_md5_sum}" ] &&  return 0 

    /etc/init.d/wpsd restart > /dev/null 2>&1 &
}
