#!/bin/sh

[ "$POINT" == "END" ] || exit 0;

if [ "$SRCMODE" = "NONE" -o "$SRCMODE" = "RE" ] && [ "$DSTMODE" = "FAP" -o "$DSTMODE" = "HAP" ]; then
    MODE=RE2AP
elif [ "$SRCMODE" = "NONE" -o "$SRCMODE" = "FAP" -o "$SRCMODE" = "HAP" ] && [ "$DSTMODE" = "RE" ]; then
    MODE=AP2RE
fi

if [ "$MODE" = "RE2AP" -o "$MODE" = "AP2RE" ]; then
    /etc/init.d/apsd restart
fi
