#!/bin/sh

if [ "$SRCMODE" = "NONE" -o "$SRCMODE" = "RE" ] && [ "$DSTMODE" = "FAP" -o "$DSTMODE" = "HAP" ]; then
    MODE=RE2AP
elif [ "$SRCMODE" = "NONE" -o "$SRCMODE" = "FAP" -o "$SRCMODE" = "HAP" ] && [ "$DSTMODE" = "RE" ]; then
    MODE=AP2RE
fi

if [ "$POINT" != "END" ] || [ "$MODE" != "RE2AP" -a "$MODE" != "AP2RE" ]; then
    exit 0
fi

# ethernet root device name, e.g. eth0/eth1
# H70X use eth0
eth_root=$(uci -c /etc/profile.d/ get profile.@DEVINFO[0].eth_root)
[ -z "$eth_root" ] && { eth_root=eth1; }

config_load sysmode
config_get sysmode sysmode mode 'Router'
config_clear

if [ "$sysmode" = "Router" ]; then 
	config_load iptv_v2
	config_get iptv_enable info enable "0"
	config_get iptv_type info iptv_type "normal"

	if [ "$iptv_enable" == 1 ] || [ "$iptv_type" == "bridge" ]; then
		local device_id=$(getfirm DEV_ID)
		local iptv_port

		if [ "$MODE" = "AP2RE" ]; then
			local iptv_eth_backhaul_vid
			local is_port_exist_brwan
			iptv_eth_backhaul_vid=$(uci -c /etc/vlan.d get vlan.iptv_eth_backhaul.vid)
			if [ -n "$iptv_eth_backhaul_vid" ]; then
				is_port_exist_brwan=$(brctl show br-wan | grep "$eth_root.$iptv_eth_backhaul_vid")
				[ -n "$is_port_exist_brwan" ] && {
					brctl delif br-wan "$eth_root.$iptv_eth_backhaul_vid"
					brctl addif br-iptv "$eth_root.$iptv_eth_backhaul_vid"
				}
			fi
		fi


		. /lib/iptv/iptv.sh
		count_self_iptv_ports "$device_id" iptv_port

		if [ "$iptv_port" != "other" ] || [ "$iptv_type" == "bridge" ]; then
			/etc/init.d/iptv restart
			# /etc/init.d/apsd restart
		fi

	fi

fi



