#!/bin/sh
# Copyright (c) 2017 Shenzhen TP-LINK Technologies Co.Ltd.
# Author		Wang Hao<wanghao@tp-link.com.cn>

[ "$DEVICE" == "lo" ] && exit 0

if [ "$INTERFACE" == "wan" ]; then
            ubus call online_test update
fi

return 0
