#!/bin/sh
# Copyright (c) 2014 The Linux Foundation. All rights reserved.

[ "$DEVICE" == "lo" ] && exit 0

[ ! -f "/tmp/improxy.pid" ] && exit 0

. /lib/functions.sh

/etc/init.d/improxy enabled && [ "$ACTION" = "ifup" ] && {
	/etc/init.d/improxy restart
}

