#!/bin/sh

[ "$INTERFACE" != "wan" -a "$INTERFACE" != "internet" ] && exit 0

. /lib/functions.sh

config_load network
config_get proto internet proto "none"

if [[ "$proto" != "none" && "$INTERFACE" == "internet" ]]; then
	config_get mtu internet mru
elif [[ "$proto" == "none" && "$INTERFACE" == "wan" ]]; then
	# 1500 - 40(v6_hdr)
	if [[ "$DEVICE" == "v6plus-wan" || "$DEVICE" == "dslt-wan" ]]; then
		mtu=1460
	else
		config_get mtu wan mtu
	fi
else
	exit 0
fi

if [[ "$ACTION" == "ifup" ]]; then
	# fw unsetmss
	fw setmss $((mtu-40))

	if [[ "$DEVICE" == "v6plus-wan" || "$DEVICE" == "dslt-wan" ]]; then
		fw s_add 4 m OUTPUT zone_wan_MSSFIX ^
	fi
elif [[ "$ACTION" == "ifdown" ]]; then
	fw unsetmss
	fw s_del 4 m OUTPUT zone_wan_MSSFIX
fi

exit 0
