#!/usr/bin/lua

local cal_offset = 0xf000
local mtd_art = io.popen("cat /proc/mtd | grep 'radio' | grep -o 'mtd.'")
local file = nil
local magic_cal = "calibrated"

if mtd_art then
        file = io.open("/dev/" .. string.gsub(mtd_art:read("*all"),"\n",""), "wb")
        mtd_art:close()
end

if file == nil then
        print("nil file")
else
        file:seek("set", cal_offset)
        file:write(magic_cal)
        file:flush()
        file:close()
end