#!/bin/sh
# Copyright (C) 2006 OpenWrt.org


usage() {
	cat <<EOF
Usage: $0 interface ssid encrption password
example:
    $0 apcli0 m5_test 0
    $0 apcli0 m5_test 1 12345678
EOF
	exit 1
}

wifi_connect_cmd() {
	local vap_name="$1"
	local conn_ssid="$2"
    local encrytion="$3"
    local password="$4"

	ifconfig $vap_name down
	ifconfig $vap_name up

	echo "vapname($vap_name) conn_ssid($conn_ssid) encrytion($encrytion) password($password)" > /dev/console

	iwpriv $vap_name set ApCliEnable=0
	iwpriv $vap_name set MACRepeaterEn=0
	iwpriv $vap_name set ApCliMWDS=1

	if [ "$encrytion" = 0 ]; then
		iwpriv $vap_name set ApCliAuthMode=OPEN
		iwpriv $vap_name set ApCliEncrypType=NONE
		echo "no encrytion================" > /dev/console
	else
		iwpriv $vap_name set ApCliAuthMode=WPA2PSK
		iwpriv $vap_name set ApCliEncrypType=AES
		iwpriv $vap_name set "ApCliWPAPSK=$password"
		echo "encrytion================" > /dev/console
    fi
	iwpriv $vap_name set "ApCliSsid=$conn_ssid"
	iwpriv $vap_name set ApCliEnable=1
}



DEVICES=
DRIVERS=


case "$1" in
	apcli0) wifi_connect_cmd "apcli0" "$2" "$3" "$4";;
    apclix0) wifi_connect_cmd "apclix0" "$2" "$3" "$4";;
	--help|help) usage;;
	*)
esac
