#!/bin/sh

# https: This starts and stops https.
#
# chkconfig: 2345 80 20
# description: https
#
# processname: /bin/stunnel

# automatically export variables to the environment
set -a

PATH=/sbin:/bin:/usr/sbin:/usr/bin

http_port=`/usr/sbin/userconfig -read HTTP Port`
https_port=`/usr/sbin/userconfig -read HTTPS Port`
https_enable=`/usr/sbin/userconfig -read HTTPS Enable`
device_ip=`ifconfig br0 2>/dev/null|awk '/inet addr:/ {print $2}'|sed 's/addr://'`
if [ -z $https_port ]; then
        https_port=443
fi

if [ -z $http_port ]; then
        http_port=80
fi
/usr/sbin/cfg -a w -p /var stunnel-https.conf https accept $device_ip:$https_port
/usr/sbin/cfg -a w -p /var stunnel-https.conf https connect $device_ip:$http_port
/usr/sbin/cfg -a w -p /var stunnel-https.conf localhttps accept 127.0.0.1:$https_port
/usr/sbin/cfg -a w -p /var stunnel-https.conf localhttps connect 127.0.0.1:$http_port

start() {
	if [ $https_enable = 0x01 ]; then
		echo "Starting https..."
		/bin/stunnel /var/stunnel-https.conf &
	fi
}

stop() {
	/bin/kill `pidof stunnel`
}

restart() {
	stop
	sleep 1
	start
}

reload() {
	echo -n "Reloading httpd for https... "
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	reload)
		reload
		;;	
	*)
		echo $"Usage $0 {start|stop|restart|reload}"
		exit 1
esac

exit $?
