#!/usr/bin/lua

-- get new dst rules from cloud and update.

local sys   = require "luci.sys"
local dbg   = require "luci.tools.debug"
local times = require "luci.model.app_timesetting"

-- 1. update dst
times.ts_update_dst()

-- 2. load tz and dst to /etc/TZ
luci.sys.exec("/lib/time_settings/set_time")
