#!/usr/bin/lua

local dbg = require "luci.tools.debug"
local uci = require "luci.model.uci"
local cfg = require "luci.sys.config"
local mode = require "luci.model.mode" 

local uci_r = uci.cursor_state()

local plc_support = mode.is_plc_support()
plc_bkhl_vlanid = arg[1]

if  plc_support == true and plc_bkhl_vlanid ~= nil then
    dbg.print("set plc_sync.vlan.backhaul_vlan_id = " .. plc_bkhl_vlanid)
    uci_r:set("plc_sync", "vlan", "backhaul_vlan_id", plc_bkhl_vlanid)
    uci_r:commit("plc_sync")
    cfg.save_config_version(0)
end

