#!/usr/bin/lua

-- check ntp update successfully.

local dbg   = require "luci.tools.debug"
local msg	= require "luci.model.message_center"

dbg.print("msg_handle_ntp_success_events")

local msg_s = msg.Msgcenter()
msg_s:handle_ntp_success_events()

