#!/usr/bin/lua

local sys   = require "luci.sys"
local nixio = require "nixio"
local dbg   = require "luci.tools.debug"
local json = require "luci.json"
local io    = require "io"
local ubus   = require "ubus"

local BCM_HOST_VAPNAME = "wl02"
local BCM_TYPE_FILE = "/tmp/g_wifi_type_bcm"

local function wifi_is_up()
	local wifi_up = false
	local fp = io.popen("iwconfig ath0")
	
	if not fp then
		return false
	end
	
	for line in fp:lines() do
		local bit_rate = string.match(line, "^%s*Bit Rate:(%d+)%s*")
		if bit_rate then
			if tonumber(bit_rate) > 0 then
				wifi_up = true
			end
			break
		end
	end
	
	fp:close()
	
	return wifi_up
end

local function wifi_is_up_bcm()
	local wifi_up = false

    local cmd = "brctl show | grep " .. BCM_HOST_VAPNAME
    local info = sys.exec(cmd)
    local bridge_on = string.find(info, BCM_HOST_VAPNAME)

    if not bridge_on then
        return false
    end

    cmd = "wl -i " .. BCM_HOST_VAPNAME .. " bss"
    info = sys.exec(cmd)
    local bss_up = string.find(info, "up")

    if bss_up then
        wifi_up = true
    end

	return wifi_up
end

local function notify_check_client()
	local _ubus = ubus.connect()
	
	dbg.print("notify_check_client: current time is "..os.time())
	_ubus:call("client_mgmt", "trigger_check", {})
	
	_ubus:close()
end

local wait_times = 0
local triggers_open = false

while wait_times < 60 do
	if not nixio.fs.access(BCM_TYPE_FILE) then
		triggers_open = wifi_is_up()
	else
		triggers_open = wifi_is_up_bcm()
	end

	if triggers_open == true then
		break
	end
	sys.call("sleep 1")
	wait_times = wait_times + 1
end
sys.call("sleep 45")
notify_check_client()
sys.call("sleep 6")
sys.call("touch /tmp/client_mgmt/client_triggers_opened")
dbg.print("client triggers is opened.")