#!/usr/bin/lua

-- push monthly report to cloud

local dbg   = require "luci.tools.debug"
local sys   = require "luci.sys"
local cloud = require "luci.controller.admin.mobile_app.cloud"

local uci_s = uci.cursor()

local MAX_CHECK_TIME = 3
local MIN_CHECK_INTERVAL = 3

local CLOUD_PUSH_LOCK = "/var/run/cloud_push.lock"
local RWLocker = require("luci.model.locker").RWLocker

local locker = RWLocker(CLOUD_PUSH_LOCK)
locker:wlock()

dbg.print("push_monthly_msg")

local form = {}
form.form = "message"
form.operation = "push"

local push_done = false
local res = cloud.dispatch(form)
if res and res.error_code == 0 then
	push_done = true
end

local check_time = 1
local check_interval = MIN_CHECK_INTERVAL
while not push_done and check_time < MAX_CHECK_TIME do	
	sys.call("sleep %d" % check_interval)	
	check_interval = check_interval * 2
	check_time = check_time + 1

	res = cloud.dispatch(form)
	if res and res.error_code == 0 then
		push_done = true
	end
end

locker:ulock()

